### ISSUE TITLE
Add option to avoid auto lowercase

### ISSUE THREAD

**Issue by orlos** [ali-saleem/anchorme.js#12]
When using th eplugin with twitter content and youtube URLs, it got broken when id are all transformed to lowercase.

**Comment by alexcorvi** [comment]
I can't reproduce the problem.
Current version of `anchorme.js` doesn't lowercase the URL.

``` javascript

anchorme.js("http://WWW.YOUtube.com/watch?v=wJUXLqNHCaI");

/*
should return: 
"<a href='http://WWW.YOUtube.com/watch?v=wJUXLqNHCaI'>http://WWW.YOUtube.com/watch?v=wJUXLqNHCaI</a>"
*/
```

**Comment by alexcorvi** [comment]
Please check the new version.
