### ISSUE TITLE
link strings surrounded by underscore don't always work

### ISSUE THREAD

**Issue by rhysburnie** [ali-saleem/anchorme.js#121]
This bug can be reproduced in the live demo:

![image](https://user-images.githubusercontent.com/245933/171334560-d72ee0cd-ef35-42ee-8502-f29e5a4b26e4.png)

```
_google.com_
_google.com.au_
some.person@domain.com.au
_some.person@domain.com.au_

*google.com*
*google.com.au*
some.person@domain.com.au
*some.person@domain.com.au*
```

The 2nd is due to the trailing `_` I would assume tld's cant have `_` in them so maybe that something that can be handled

The 4th is due to the `_` at start (tho Im confused why `.au` is excluded, perhaps emails can start with `_` tho not sure if they do I would assume that its a rare thing

**Comment by alexcorvi** [comment]
Solved in latest release 3.0.4, However keep in mind that an email can begin with an underscore.
