### ISSUE TITLE
URLs ending with hyphen exclude hyphen

### ISSUE THREAD

**Issue by Anwinity** [ali-saleem/anchorme.js#125]
```
import anchorme from "anchorme";

const url = "Some text with some urls https://example.com/ABC-123 and https://example.com/ABC- blah blah blah";
const result = anchorme({
    input: url,
    options: {
        attributes: {
            target: "_blank"
        }
    }
});

console.log(result);
```

INPUT:
`Some text with some urls https://example.com/ABC-123 and https://example.com/ABC- blah blah blah`
OUTPUT:
`Some text with some urls <a target="_blank" href="https://example.com/ABC-123">https://example.com/ABC-123</a> and <a target="_blank" href="https://example.com/ABC">https://example.com/ABC</a>- blah blah blah`

**Comment by alexcorvi** [comment]
Solved in the latest version 3.0.2.
