### ISSUE TITLE
The content came with Img tag and this library wrap img src link anchor tag

### ISSUE THREAD

**Issue by krupal1710** [ali-saleem/anchorme.js#129]
Test case 1
if I pass this to anchorme, 

`<img src="https://media.gettyimages.com/id/103201937/photo/sunset-at-2nd-hoogly-bridge.jpg?s=612x612&w=gi&k=20&c=vk1MpW3sw8DQuobfz5JLBHvlbOTVVVQZ5tf5MihM1aM=" alt="undefined" style="height: auto;width: auto"/>`

it convert it to

```<img src="<a href="https://media.gettyimages.com/id/103201937/photo/sunset-at-2nd-hoogly-bridge.jpg?s=612x612&w=gi&k=20&c=vk1MpW3sw8DQuobfz5JLBHvlbOTVVVQZ5tf5MihM1aM">https://media.gettyimages.com/id/103201937/photo/sunset-at-2nd-hoogly-bridge.jpg?s=612x612&w=gi&k=20&c=vk1MpW3sw8DQuobfz5JLBHvlbOTVVVQZ5tf5MihM1aM</a>=" alt="undefined" style="height: auto;width: auto"/>```

Test case 2
if I pass this to anchorme,

`<img src="https://picsum.photos/200/300" />`

it convert it to

`<img src="https://picsum.photos/200/300" />`

so for 2nd test case its works fine, but for 1st test case it wont work.
I guess its due to '-' in the user

**Comment by alexcorvi** [comment]
Solved in the latest version 3.0.2.
