### ISSUE TITLE
Reference to mocha in index.d.ts

### ISSUE THREAD

**Issue by sherlock1982** [ali-saleem/anchorme.js#135]
`node/index.d.ts` now has reference to mocha. This is strange :-)

It means you can't really use it with typescript if you don't reference `@types/mocha` which is undesirable in many cases.

**Comment by watsom27** [comment]
Bump, this is slightly irritating having to add another dependency to get this to build :(

**Comment by alexcorvi** [comment]
Fixed! sorry for such inconvenience
