### ISSUE TITLE
Anchor tag recursion

### ISSUE THREAD

**Issue by ghost** [ali-saleem/anchorme.js#17]
There seems to be an issue by having an anchor tag with the URL as its content. We're using anchorme with a rich text editing library, which insert an anchor html element with the content being a URL string:
`<a href="http://www.google.com">http://www.google.com</a>`

Anchorme will place another tag inside the existing tag. This will recurse each time the string is parsed. 

I realise that the library's core function is to find URL strings and wrap them, so this might not be the best use for it or even an issue really, but is there a (quick) workaround for this issue? 
Maybe an option like _ignoreUrlsInTags_ could be added?

**Comment by alexcorvi** [comment]
Fixed.. Thanks for bringing this to my attention.
