### ISSUE TITLE
Link to performance tests

### ISSUE THREAD

**Issue by dandv** [ali-saleem/anchorme.js#2]
> Tested against Autolinker.js and linkifyjs on FireFox. After 10000 iterations anchorme.js scored 300ms while others where around 1200

Would love to see the tests, and what the performance differences are in Chrome.

(I've added this library to [my StackOverflow answer on replacing plain URLs with strings](http://stackoverflow.com/questions/37684/how-to-replace-plain-urls-with-links/21925491#21925491)).

**Comment by alexcorvi** [comment]
Performance comparisons are now available on the [demo page](http://ali-saleem.github.io/anchorme.js/).
