### ISSUE TITLE
Cannot find module 'anchorme.js'

### ISSUE THREAD

**Issue by dsavenko** [ali-saleem/anchorme.js#20]
Hi,

How to use it with Node/npm? `require('anchorme.js')` always throws `Error: Cannot find module 'anchorme.js'`. I assume, this is because the name ends with `.js`.

Node version: v6.4.0

**Comment by t2n** [comment]
fails like this in browserify as well : - D

**Comment by alexcorvi** [comment]
please check 0.0.7
install via npm through this command: `npm install --save anchorme`
