### ISSUE TITLE
Single hostname isn't linked

### ISSUE THREAD

**Issue by liorbrauer** [ali-saleem/anchorme.js#23]
Hi,

I have a use case with the following string: 

`http://tfs:8080/_ab/`

It is not highlighting without a `.` in the hostname, but I think it should highlight if it detects the `http://` protocol part

**Comment by alexcorvi** [comment]
Fixed check 0.7.1

**Comment by liorbrauer** [comment]
Wow, amazing response time! Thank you very much! 👍

**Comment by mhodnick-spok** [comment]
I cannot get this feature to work. Tried it using the embeddded `anchorme` on the anchrome.js documentation site and it does not work: 

```
anchorme.validate.url("http://machinename/resource") // returns false
```

Any ideas?

**Comment by viking2917** [comment]
@mhodnick-spok is 'http://machinename/resource' a legitimate URL? I use anchorme and it works for me very well. I wonder if you change that to a legitimate url it might work?
