### ISSUE TITLE
Adding non-complete IP produces an error

### ISSUE THREAD

**Issue by daniellereya** [ali-saleem/anchorme.js#24]
Try entering the following value: 12.12.12.
You'll get the following error:
![image](https://cloud.githubusercontent.com/assets/16049491/20864555/c2be5b3c-b9fe-11e6-801f-ae7d5d54ec38.png)

**Comment by alexcorvi** [comment]
Fixed. Thank you for bringing this to my attention! much appreciated.
Please update to 0.7.2
