### ISSUE TITLE
Need to add _blank conditionally. Right now it is being added even for mailto://

### ISSUE THREAD

**Issue by Sumeetgrg** [ali-saleem/anchorme.js#29]
Hi,

If we apply target= "_blank" in the attributes, we are getting target attribute added even for text converted to mailto:// . 

for example:
```
anchorme("drop an email to sgrg@abc.com", {
                    attributes: {
                        "target": "_blank"
                    }
                }) 
```

**Output**:"`drop an email to <a href='mailto:sgrg@abc.com' target='_blank' >mailto:sgrg@abc.com</a>`"

**Problem**: _It is unnecessarily opening a blank window on click._

Should there be someway, we can ignore the adding target attribute for email?

-Sumeet

**Comment by Sumeetgrg** [comment]
Thanks Alex,

Is there a workaround you would like to suggest?

**Comment by alexcorvi** [comment]
It's fixed now. update to 0.8.0

Although the API is bit changed now, but you can do this:

```javascript
anchorme(string,{
    attributes:[
        // plain object for simple attribute adding
        {
            name:"class",
            value:"link"
        },
        // a function for conditionally adding attributes
        function(data){
            if(data.protocol !== "mailto:") return {name:"target",value:"blank"};
            // following conditions can also be used:
            // if(data.raw.indexOf("@") > 0) return {name:"target",value:"blank"};
            // if(data.reason !== "email") return {name:"target",value:"blank"};
        }
    ]
});
```

For more about this change please refer to the readme.md file https://github.com/alexcorvi/anchorme.js#adding-attributes


Your comments are much appreciated!
