### ISSUE TITLE
Feature request: When truncating, put ellipsis in middle

### ISSUE THREAD

**Issue by fknorn** [ali-saleem/anchorme.js#30]
Hi there,

Love the truncation option, but would it be possible even to have the ellipsis in the middle of the cut down URL (e.g. `http://www.go...bla=blub&nice=1)` instead of at the end, and maybe even drop the protocol from it too? All in order to make the shortened version even more useful and indicative of the actual link...

Cheers!

**Comment by alexcorvi** [comment]
[Implemented in 0.8.3](https://github.com/alexcorvi/anchorme.js#truncate-from-the-middle), see [this fiddle for demonstration](https://jsfiddle.net/h8vrpvLc/)

**Comment by fknorn** [comment]
Oh, sweet, thanks :-)
