### ISSUE TITLE
URLs that end in a period, the period becomes part of the URL.

### ISSUE THREAD

**Issue by olafjanssen** [ali-saleem/anchorme.js#4]
Many people add url at the end of their sentence and then the url ends in a period, such as http://codepen.io/sdthornton/pen/wBZdXq.

The period then becomes part of the link and the link won't work. While the '.' is a valid character in URLs, it is not part of the allowed base64 set and I suspect that very few actual urls will end in a period.

**Comment by alexcorvi** [comment]
Fixed in the new patch.
