### ISSUE TITLE
Converting invalid format into link

### ISSUE THREAD

**Issue by yojnajain** [ali-saleem/anchorme.js#41]
Eg: yojna...oracle, care...to, core...so

Above provided examples are getting converted into link.

**Comment by alexcorvi** [comment]
Hi,
I'm unable to reproduce this. Can you demonstrate this on runkit or JSFiddle?

Here's what I'm getting on runkit: [link](https://runkit.com/5883d43c0629220014e29ca2/58b91f0bb119c600143222f7).

What version of anchorme are you using? current version is `1.0.4`. Also, when installing via NPM please install `anchorme` not `anchorme.js`.
