### ISSUE TITLE
Problem with excluding files

### ISSUE THREAD

**Issue by Sumeetgrg** [ali-saleem/anchorme.js#46]
Hi,

We are facing issues with files converted to links. For example:
**download.zip** is getting converted to: **`<a href="http://download.zip" >download.zip</a>`**

We came across with property, [files:false](https://alexcorvi.github.io/anchorme.js/#excluding) but it seems doesn't work:
[jsFiddle](https://jsfiddle.net/gydnngrz/2/)

Please help.

**Comment by alexcorvi** [comment]
The `files:false` option doesn't exclude URLs that points to files on the internet, It excludes local files URLs like `file:///Users/alex/something.html`.

**Comment by Sumeetgrg** [comment]
It seems, the issue is because of .zip TLD. 
It is  converting each message with "something.zip" to Anchor link.

Is there a workaround you may suggest?

**Comment by alexcorvi** [comment]
I've added a custom exclusion function.

Each identified URL will go through this function. The function can be used to test the URLs and return a truthy value (`true` or `1` or `"non-empty string"` ... etc) to exclude or a falsy value (`false` or `1` or `undefined` ... etc) to include.

Here's an example:

```javascript
anchorme("something.zip",{
    exclude:function(URLObj){
        return URLObj.endsWith(".zip");
    }
})
```
I've also [edited the JSFiddle](https://jsfiddle.net/gydnngrz/3/).

Also, here's [the relevant documentation](http://alexcorvi.github.io/anchorme.js/#custom-exclusion).

Please tell me if you have any other issues.
