### ISSUE TITLE
Link within paranthesis and normal text not converted (sometimes)

### ISSUE THREAD

**Issue by mooflu** [ali-saleem/anchorme.js#48]
Not converted:
"Do a search (go here: google.com)" 

Converted (added an extra space after google.com):
"Do a search (go here: google.com )"

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
