### ISSUE TITLE
percent in url gets encoded twice

### ISSUE THREAD

**Issue by mooflu** [ali-saleem/anchorme.js#49]
running 'en.wiktionary.org/wiki/銀' through anchorme works fine, however if you go to that link in a browser and copy and paste it the actual string is already encoded:
'https://en.wiktionary.org/wiki/%E9%8A%80'
If you run the latter through anchorme, the link ends up as 
'https://en.wiktionary.org/wiki/%25E9%258A%2580'

**Comment by troutowicz** [comment]
You can abuse the `exclude` method to work around this.

```js
anchorme(value, {
  exclude: (urlObj) => {
    urlObj.encoded = urlObj.encoded.replace(/%25/g, '%');
    return false;
  },
});
```

**Comment by sadtaco** [comment]
This is still a bug, even if there is somewhat of a workaround.
The parsing should see the difference between /%80, an encoded character, and /80% which is a valid (but stupid) URL.

**Comment by rawpixel-vincent** [comment]
I think it should at least be an option to enable percent encoding or not

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
