### ISSUE TITLE
Make "localhost" into a URL

### ISSUE THREAD

**Issue by mercmobily** [ali-saleem/anchorme.js#50]
Hi,

It would be nice if the library interpreted "localhost" as a valid URL: http://localhost I am asking because we use localhost to test our web app, and it would be nice to have the links functional.

Is it possible to do it right now, with an option?

Merc.

**Comment by seishin4real** [comment]
fixed pattern for src/tests/url.ts
```
^(https?:\/\/|ftps?:\/\/)?([a-z0-9%\-]+\.|localhost\:){1,}([a-z0-9\-]+)?(:(\d{1,5}))?(\/([a-z0-9\-._~:\/\?#\[\]@!$&'\(\)\*\+,;=%]+)?)?$
```

(last commit on Apr 6, 2017 :/ )

**Comment by SalmenBejaoui** [comment]
Any update about this issue?

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
