### ISSUE TITLE
http://www.google.com?aQueryParam=blah is not supported

### ISSUE THREAD

**Issue by eyih** [ali-saleem/anchorme.js#51]
Hi, 

"http://www.google.com/?aQueryParam=blah" works fine but removing the last backslash makes it not converted to url.  

Thanks, 
Elaine

**Comment by mysublife** [comment]
Hi,

I have a similar issue with wordpress auto-generated links:
https://myblog.wordpress.com?p=459&shareadraft=5915f9235084b

The missing slash between the tld and the interrogation mark makes it fail.

(And thank you for your great lib)

**Comment by SimonChris** [comment]
This is still not working, which is a dealbreaker for me. Can we get an update from the maintainer?

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
