### ISSUE TITLE
urls without domain suffix (just a machine name) should be valid

### ISSUE THREAD

**Issue by mhodnick-spok** [ali-saleem/anchorme.js#53]
the following urls should be valid, but are not:

```
http://localhost
http://chewbacca
http://chewbacca;80
http://chewbacca:80/test
```

I used the embedded `anchorme` on the anchorme.js documentation site to test this. 

![anchorme-machine-name](https://user-images.githubusercontent.com/29961155/31080246-c01e29ec-a74d-11e7-9469-dd0dfd51f4ba.png)

**Comment by j4kim** [comment]
Any update ?
I also need this

**Comment by mea-alexanm** [comment]
Hello,

also custom domains are not recognized. We use the suffix "inside" for internal webpages and this is also not found:
http://test.domain.com works
http://test.domain.inside does not work

Thx
Markus

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
