### ISSUE TITLE
space in url

### ISSUE THREAD

**Issue by kk8401** [ali-saleem/anchorme.js#57]
Hi,

Is it possible to convert the url with space in the parameter?
eg: www.google.com?key=add value&key2=value

I tried to replace space with %20 www.google.com?key=add%20value&key2=value
the outcome for the url become
www.google.com?key=add%2520value&key2=value

**Comment by bilelz** [comment]
hello,

i resolved this by using another librairy
https://github.com/gregjacobs/Autolinker.js

regards

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
