### ISSUE TITLE
Link after emoji

### ISSUE THREAD

**Issue by albertleao** [ali-saleem/anchorme.js#58]
This is coming from a tweet. Shouldn't this be linked?

> What's the best way to clean your smartphone? 📱🚿https://t.co/cxjsA6j60J

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
