### ISSUE TITLE
Rendering does not consider links already within an anchor

### ISSUE THREAD

**Issue by kerly** [ali-saleem/anchorme.js#59]
Issue:
When text is run through the anchorme method multiple times it will nest links within the existing links.

Expected result:
Parser recognizes that the link is already within an anchor tag and does not generate a nested link.

Steps to recreate:
Run this text through anchorme:
Initial: `http://google.com`
1st render: `<a href="http://google.com" >http://google.com</a>`
2nd render: `<a href="http://google.com" ><a href="http://google.com" >http://google.com</a></a>`

**Comment by christophwolff** [comment]
Any fixes for this?

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
