### ISSUE TITLE
Using this to parse front end, like ng-repeat?

### ISSUE THREAD

**Issue by alteredorange** [ali-saleem/anchorme.js#6]
Is there any way to use this without having to convert the original variable to a anchorme.js variable?  Say for example when using angularJS and jg-repeat, is there any way to use it on text as it's being displayed?

**Comment by alexcorvi** [comment]
Here's a working fiddle implementing anchorme.js with angular.
[https://jsfiddle.net/yem6rnqp/](https://jsfiddle.net/yem6rnqp/)

I'm planning to use similar implementation on the testing page too.
