### ISSUE TITLE
Not all attributes in HTML tags are skipped.

### ISSUE THREAD

**Issue by pas-dag** [ali-saleem/anchorme.js#64]
Here's an example of a tag that gets mangled (this is excerpted from a google calendar email):
```<span itemprop="object" itemscope itemtype="http://schema.org/Event">```

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
