### ISSUE TITLE
anchorme is not defined

### ISSUE THREAD

**Issue by KlaasT** [ali-saleem/anchorme.js#66]
Hi,

I have two .js files. One from anchorme and the second one is called chat.js with a couple of functions. I've included both to my html page:

<script src="/js/anchorme.js" type="text/javascript"></script>
<script src="/js/chat.js" type="text/javascript"></script>

However when trying to call anchorme inside my function my browser is saying "anchorme is not defined".

Probably I am understand something completely wrong but I'm not getting it :(

Would be great if I can get a hint what to do to call anchorme correctly.

Thanks.

**Comment by BigOHenry** [comment]
Same problem here :(

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
