### ISSUE TITLE
URLs include parentheses

### ISSUE THREAD

**Issue by moek** [ali-saleem/anchorme.js#68]
Hi. Thanks for your library, it does a great job :)

One issue I found today ist, that URLs include parentheses:

for example:
`(Source: https://github.com/alexcorvi/anchorme.js/issues)`

will result in a link like this:
`(Source: <a href="https://github.com/alexcorvi/anchorme.js/issues)">https://github.com/alexcorvi/anchorme.js/issues)</a>`

I would expect this result:
`(Source: <a href="https://github.com/alexcorvi/anchorme.js/issues">https://github.com/alexcorvi/anchorme.js/issues</a>)`

This is also the result of Autolinker.js (see http://greg-jacobs.com/Autolinker.js/examples/index.html)

But actually I am not aware of how to officially handle parentheses in URLs :)

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
