### ISSUE TITLE
Suggestion: Change `tests` directory name to `checks`

### ISSUE THREAD

**Issue by vishalnarkhede** [ali-saleem/anchorme.js#70]
@alexcorvi I have a suggestion to change the name of directory `src/tests` to `src/checks` for following two reasons:

1. When the root application uses default config of `yarn autoclean`, this tests directory gets removed (`tests` ). And which in turn results breaking the application. Here is the default config for autoclean https://github.com/yarnpkg/yarn/blob/158da6c6287cbc4fee900e3704f140c3391dc28d/src/cli/commands/autoclean.js#L20
2. `tests` is a bit confusable with UI/unit tests, so I feel more explicit name such as `checks` will avoid this confusion for reader.

I am more than happy to make this change and file a pull-request. Please let me know what you guys think!

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)
