### ISSUE TITLE
Doesn't count Slash at the end

### ISSUE THREAD

**Issue by 777genius** [ali-saleem/anchorme.js#71]
Hi, nice lib! I will use it in my project.

For example, for this link: http://alexcorvi.github.io/anchorme.js/, the slash at the end will be missed. I wonder if this makes sense or is it a bug? Github highlights my link.

**Comment by Ken-Gilb** [comment]
I am having this same problem. When providing a link with a trailing slash, the anchor tag is excluding the training slash leaving it outside of the hyperlink. Maybe include an option to remove trailing slashes or include them in the link itself

**Comment by alexcorvi** [comment]
Thank you for the report.
fixed in [2.1.1](https://github.com/alexcorvi/anchorme.js/releases/tag/2.1.1).
