### ISSUE TITLE
Invalid result when using anchors with non standard attributes

### ISSUE THREAD

**Issue by diegobanuelos** [ali-saleem/anchorme.js#72]
Hi, great library. When making tests using your project I noticed an invalid result with the following case:

`<a href="https://www.validurl.com" data-saferedirecturl="https://www.validurl.com/file.png">Valid text</a>`

Reviewing your code, I added the attribute *data-saferedirecturl* to the **htmlAttributes** array in the dictionary and It worked; however, it will resolve only this specific case and not others with different non standard attribute names. What do you think about making the function **isInsideAnchorTag** ignore all the urls inside any property of an anchor?

**Comment by alexcorvi** [comment]
Thank you for the report.
fixed in [2.1.1](https://github.com/alexcorvi/anchorme.js/releases/tag/2.1.1).
