### ISSUE TITLE
missing {list: true} option in v2

### ISSUE THREAD

**Issue by mahboubii** [ali-saleem/anchorme.js#74]
v1 had this super useful feature where you could get an array of URLs with raw and encoded value within a string by passing `list: true` to the options which is missing in the v2 version of the library. 
(the new `anchorme.list()` is not similar to this)

Sample code:
```

anchorme(
  'http://alexcorvi.github.io/anchorme.js/ hey http://alexcorvi.github.io/',
  { list: true },
);

// output
[
  {
    reason: 'url',
    protocol: 'http://',
    raw: 'http://alexcorvi.github.io/anchorme.js/',
    encoded: 'alexcorvi.github.io/anchorme.js/'
  },
  {
    reason: 'url',
    protocol: 'http://',
    raw: 'http://alexcorvi.github.io/',
    encoded: 'alexcorvi.github.io/'
  }
]
```

**Comment by alexcorvi** [comment]
You might want to have a look at the [2.1.1 version release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.1.1). the `anchorme.list` feature is exposing a lot more information now. `protocol` & `reason` among many other properties. I hope this would help.
