### ISSUE TITLE
Library breaks url in style in HTML code

### ISSUE THREAD

**Issue by cedtaz** [ali-saleem/anchorme.js#75]
Hey, 

I have to anchor a mail in HTML. But this kind of code : 
`<div style="background-image: url('http://mysite.com/images/test-background.gif');`
with the library : 
`<div style="background-image: url('<a href="http://mysite.com/images/test-background.gif">http://mysite.com/images/test-background.gif</a>');`

And it breaks the HTML.

I tested with the options but nothing...

Is there a way with the current library to do this ?

Thanks.

Cedric A.

**Comment by alexcorvi** [comment]
Thank you for the report.
fixed in [2.1.1](https://github.com/alexcorvi/anchorme.js/releases/tag/2.1.1).
