### ISSUE TITLE
Problem with data-attributes

### ISSUE THREAD

**Issue by cedtaz** [ali-saleem/anchorme.js#76]
Library breaks the HTML when url are set in data-attributes.

Ex:
`<table data-thumb="http://mysite.com"></table>`
=>
`<table data-thumb="<a href="http://mysite.com">http://mysite.com</a>"></table>`

Thanks

**Comment by alexcorvi** [comment]
Thank you for the report.
fixed in [2.1.1](https://github.com/alexcorvi/anchorme.js/releases/tag/2.1.1).
