### ISSUE TITLE
Track anchor type by matched position instead of testing regex again

### ISSUE THREAD

**Issue by pimlie** [ali-saleem/anchorme.js#77]
Performance could probably be improved a little bit if you dont test the regex'es here again: https://github.com/alexcorvi/anchorme.js/blob/gh-pages/src/transform.ts#L45

Instead you could make sure to wrap all individual protocol regexes [in finalRegex](https://github.com/alexcorvi/anchorme.js/blob/gh-pages/src/regex.ts#L22) as a group (currently only $url is a group), then check which [index in result](https://github.com/alexcorvi/anchorme.js/blob/gh-pages/src/index.ts#L11) contains a value. Eg with the current regexes result[1] would be a normal link, result[56] an email and result[64] a file.

**Comment by alexcorvi** [comment]
Thank you for the suggestion.
Implemented in [2.1.1](https://github.com/alexcorvi/anchorme.js/releases/tag/2.1.1), starting from this release the library will use the matched position to extract more details about the link, and will expose those details at `anchorme.list` & at the conditional options parameters as the second argument.
Documentation is still lacking though.
