### ISSUE TITLE
Override country code top level domain to normal string

### ISSUE THREAD

**Issue by widirizki** [ali-saleem/anchorme.js#79]
Hey,

I have a case with academic degree as shown below:
```
let input = "Alex, M.Sc";
```
the academic title becomes a link because it is a country code for Seychelles.
https://www.iana.org/domains/root/db/sc.html

is there a way to override country code to normal string?

Thank you.

**Comment by alexcorvi** [comment]
Sure, using the `exclude` option.
- Documentation: http://alexcorvi.github.io/anchorme.js/#excluding
- JSFiddle: https://jsfiddle.net/h9x452pd/
