### ISSUE TITLE
Percent-encoding breaks URLs

### ISSUE THREAD

**Issue by davidschlachter** [ali-saleem/anchorme.js#8]
Some of the documents on our file server have spaces in their URL, e.g.

```
https://mydomain.com/My%20document.pdf
```

An URL with a percent sign is not recognized by anchorme.

e.g. 

`> anchorme.js("https://mydomain.com/My%20document.pdf");`
`< "https://mydomain.com/My%20document.pdf"`

`> anchorme.js("https://mydomain.com/My20document.pdf");`
`< "<a href='https://mydomain.com/My20document.pdf'>https://mydomain.com/My20document.pdf</a>"`

**Comment by alexcorvi** [comment]
Merged pull request. Fixed

**Comment by bennlich** [comment]
Does not seem fixed anymore :/ See https://github.com/alexcorvi/anchorme.js/issues/57
