### ISSUE TITLE
Performance issue with testing/finding regex indexes

### ISSUE THREAD

**Issue by pimlie** [ali-saleem/anchorme.js#84]
Testing to find the correct regex indexes shouldnt be a runtime feature: https://github.com/alexcorvi/anchorme.js/blob/gh-pages/src/regex.ts#L80

After this pkg has been build for publishing it shouldnt be possible that the regex indexes change, so it would be better to just add a test to make sure that the indexes are correct and then in the production build include a static list of indexes.

**Comment by alexcorvi** [comment]
fixed since 3.0
