### ISSUE TITLE
Miss some url patterns from angularjs

### ISSUE THREAD

**Issue by wushaobo** [ali-saleem/anchorme.js#86]
I found this awesome lib does not fit for some url patterns , especially from Angularjs.

Works:
`http://example.com/#/some/path?foo=bar`

Not works:
`http://example.com/#/`
`https://ci.hpapps.cn/go/pipelines#!/`

**Comment by thexeos** [comment]
![image](https://user-images.githubusercontent.com/2260539/91628606-3e336a80-e9b9-11ea-85cc-2ad485d71626.png)

This is the portion of regex where matching fails. And a couple more cases that it skips.

The culprit - `\b`. It expects word boundary at the end of the pathname match, however there is no word boundary between `/` character and any other non-word character (as `/` is not a word character itself, and neither is `#`).

Solution is changing `\b` to `(?=[^a-zA-Z\d\-._~\!$&*+,;=:@%'"\[\]()\/?]|$)`, or `(?=[^${allowedInPath}\/?]|$)` when in code (or its Unicode counterpart). ~~I will submit a PR for this change.~~

Edit: As always, there are edge cases. There is also some spec uncompliance that was built in, which means a lot of hacks that are in the code and regexps are to stay. I am no longer sure there is a reliable regex-only fix for this. It sure exists, but likely not as a drop-in replacement.

**Comment by alexcorvi** [comment]
fixed since 3.0
